---
golang_version: 1.4.1
golang_download_url: https://storage.googleapis.com/golang/go{{ golang_version }}.linux-amd64.tar.gz
golang_install_prefix: /usr/local
goroot: "{{ golang_install_prefix }}/go"