---

- name: create stucco GOPATH directory for document-service
  file: path={{ gopath }}/src/github.com/stucco/document-service owner={{ stucco_user }} group={{ stucco_group }} state=directory mode=4777 recurse=yes

- name: download document-service repo
  git: repo=https://github.com/stucco/document-service.git dest={{ gopath }}/src/github.com/stucco/document-service

- name: test document-service
  shell: "(GOPATH={{ gopath }} {{ goroot }}/bin/go run doc-service.go -port=8267 &) && sleep 2 && GOPATH={{ gopath }} {{ goroot }}/bin/go test -timeout 30s chdir={{ gopath }}/src/github.com/stucco/document-service"

- name: build document-service
  shell: "GOPATH={{ gopath }} {{ goroot }}/bin/go build doc-service.go chdir={{ gopath }}/src/github.com/stucco/document-service"

- name: install document-service
  file: src={{ gopath }}/src/github.com/stucco/document-service/doc-service dest={{ stucco_bin }}/doc-service state=link

# START SERVICES
- name: copy document-service supervisord config
  template: src=supervisor/stucco-doc.conf dest=/etc/supervisor/conf.d/stucco-doc.conf
- name: reload supervisord
  shell: /usr/bin/supervisorctl reload
