---

- name: Download titan graph database
  get_url: url={{ titan_download_url }} dest={{ titan_download_dir }}/titan.zip

- name: Set up the directory
  file: path={{ titan_dir }} state=directory

- name: Unarchive the zip file
  unarchive: >
    copy=no
    src={{ titan_download_dir }}/titan.zip
    dest={{ titan_prefix }}

- name: Remove the zip file
  file: path={{ titan_download_dir }}/titan.zip state=absent

- name: Copy the rexster script
  copy: src=rexster.sh dest={{ titan_path }}/bin mode=0755

- name: Copy the rexster configuration template
  template: src=conf/rexster-cassandra-es.xml dest={{ titan_path }}/conf/rexster-cassandra-es.xml

- name: Copy the init script template
  template: src=etc/init.d/titan dest=/etc/init.d/titan owner=root mode=0755
  notify: start titan

- name: enable titan server to survive reboot
  service: name=titan enabled=yes