---
galaxy_info:
  author: John Goodall
  description: An Ansible role for installing Stucco collectors on Ubuntu.
  company: Oak Ridge National Laboratory
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - 7
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
dependencies:
  - { role: stucco.common }
  - { role: smola.java, java_packages: [oracle-java7-installer, oracle-java7-set-default] }
  - { role: jgoodall.maven3, maven_version: 3.1.1 }
