structured_data:
  exchange: {{ rabbitmq_exchange }}
  host: {{ rabbitmq_host }}
  port: {{ rabbitmq_port }}
  username: {{ rabbitmq_user }}
  password: {{ rabbitmq_password }}
  queue: stucco-in-structured
  emptyQueueSleepTime: 90000
  persistent: true
  bindings: 
      - stucco.in.structured.#

unstructured_data:
  exchange: {{ rabbitmq_exchange }}
  host: {{ rabbitmq_host }}
  port: {{ rabbitmq_port }}
  username: {{ rabbitmq_user }}
  password: {{ rabbitmq_password }}
  queue: stucco-in-unstructured
  emptyQueueSleepTime: 90000
  persistent: true
  bindings:
      - stucco.in.unstructured.#

document_service:
  host: {{ stucco_doc_host }}
  port: {{ stucco_doc_port }}

database_connection:
  hostname : localhost 
  port : 5432
  database : testdb
  username : stucco
  password : "stucco"
  timeout-connection-ms : 18000
  timeout-write-ms : 4000
  timeout-read-ms : 16000 
  max-async-write-queue-size : 512000
  message-retry-count : 4
  message-retry-wait-ms : 50
  language : c
  graph-obj-name : graph
  graph-name : graph_name
  transaction : true
  serializer : 0